import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val kotlinx_serialization_runtime: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.13.0"

    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.1"

    const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.1"

    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:1.3.50"

    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.50"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50"

    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:1.3.50"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:3.6.0-beta02"

    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:1.1.1"

    const val junit_junit: String = "junit:junit:4.12"

    const val de_fayard_refreshversions_gradle_plugin: String =
            "de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:0.7.0"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:3.2.0"

    const val exifinterface: String = "androidx.exifinterface:exifinterface:1.1.0-beta01"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:26.6.0-beta02"

    const val viewpager2: String = "androidx.viewpager2:viewpager2:1.0.0-beta04"

    const val appcompat: String = "androidx.appcompat:appcompat:1.1.0"

    const val core_ktx: String = "androidx.core:core-ktx:1.1.0"

    const val timber: String = "com.jakewharton.timber:timber:4.7.1"

    const val aapt2: String = "com.android.tools.build:aapt2:3.6.0-beta02-5836729"
}
